# https://starship.rs/config

add_newline = false

format = """
$character\
$directory\
$git_branch
"""

right_format = """
$git_status\
$git_state
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
truncation_length = 1

[git_branch]
format = '[\($branch\)](bold blue) '
